### ISSUE TITLE
DT_HOST_ID required?

### ISSUE THREAD

**Issue by avdveen** [Dynatrace/heroku-buildpack-dynatrace#21]
Getting a warning that DT_HOST_ID is required when trying to add the agent on Heroku 18. The docs do not reference the need for this. The URL that needs to be used is also not clear from the docs. Since it is Heroku 18, we need to use v1.0 if I understand correctly. Should the URL be https://github.com/Dynatrace/heroku-buildpack-dynatrace.git#v1.0? We tried is as is, but it complains it cannot find the buildpack. Using the URL without # allows the build to complete, but the agent never shows up in the tenant. We've double-checked the tenant ID and API token.

**Comment by arthfl** [comment]
@avdveen 
There is currently no check for DT_HOST_ID in the heroku-buildpack, so the warning is probably coming from the OneAgent itself.
You should be able to just set that via
```bash
heroku config:set DT_HOST_ID=your_host_id
```

Other than that, where did you find that Heroku 18 requires using the v1.0 tag on the repo?

**Comment by avdveen** [comment]
There is no OneAgent deployed, yet so what should I set the host ID to then?

On the releases page, under release v1.2:
_Please note: this release works only with Heroku 20+
For previous Heroku versions, use buildpack v1.0 instead._

**Comment by arthfl** [comment]
You set it basically to the name you want to have it :-)
Example from one of our sample apps:
```bash
$ heroku config | grep DT_HOST_ID
DT_HOST_ID:   sample-heroku-go-dev
```
