### ISSUE TITLE
Large increase in oneagent size.

### ISSUE THREAD

**Issue by daveduthie** [Dynatrace/heroku-buildpack-dynatrace#24]
**Describe the bug**

The slug size of apps using this buildpack jumped by ~50MB between 1.295.70.20240820-160945 and 1.297.53.20240820-121511. This has pushed our (large) jvm app over the 500MB slug size limit. 

Using oneagent 1.295.70.20240820-160945 yields a slug of ~450MB, which once deployed looks something like this:

```
$ heroku run bash -a MY_APP
$ ls | xargs du -h -s
8.0K	bin
19M	contrast
646M	dynatrace
4.0K	Procfile
4.0K	system.properties
149M	target
```

Anything newer than 1.295.70.20240820-160945 increases the slug size to over 500MB, which heroku rejects. This has forced us to pin the oneagent version.

**To Reproduce**
1. Create a heroku app using the the dynatrace buildpack
2. Get a shell in heroku: `heroku run bash -a YOUR_APP`
3. See that oneagent consumes a lot of disk space: `du -h`.

**Expected behavior**

Oneagent should not increase the slug size so much, or the buildpack should provide a way to remove unneeded modules.

**Comment by arthfl** [comment]
We'll have a look into this.

**Comment by arthfl** [comment]
@daveduthie i can confirm the issue.
The problem is that we currently don't do any technology detection in the heroku-buildpack. Which means we always fetch the whole OneAgent package. This obviously grows over time, since features are being added constantly.

We'll invest some time to add technology detection (or at least configuration) so we can download a significantly smaller agent packge with only the required features.

**Comment by daveduthie** [comment]
@arthfl thanks!

**Comment by arthfl** [comment]
@daveduthie 
This is now solved with https://github.com/Dynatrace/heroku-buildpack-dynatrace/releases/tag/v1.4

You can now configure which specific OneAgent code module(s) you want to use, via the DT_TECHNOLOGY parameter (see updated README, i linked the relevant page in our docs with a list of supported technologies).

If something is still unclear just let me know :-)

**Comment by daveduthie** [comment]
@arthfl, thanks!

After setting `DT_TECHNOLOGY=java`, our slug size dropped from 504MB to 293.1MB.
